name: Build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    env:
      THEOS: ${{ github.workspace }}/theos
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos & SDK
        run: |
          git clone --recursive https://github.com/theos/theos.git $THEOS
          curl -L https://github.com/theos/sdks/raw/master/iPhoneOS14.5.sdk.tar.xz -o SDK.tar.xz
          mkdir -p $THEOS/sdks
          tar -xf SDK.tar.xz -C $THEOS/sdks
          # تحميل ملفات الحماية (Substrate) عشان "Exit code 1" تختفي
          curl -L https://github.com/theos/headers/archive/master.zip -o headers.zip
          unzip -o headers.zip -d $THEOS/include

      - name: Build Tweak
        run: |
          cd ${{ github.workspace }}
          make clean
          make package FINALPACKAGE=1
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Hamad-Shield-File
          path: packages/*.deb
