name: Build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    # السطر ده بيسكت أي تحذير من جيت هاب بخصوص Node
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Theos and SDK
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          curl -L https://github.com/theos/sdks/raw/master/iPhoneOS14.5.sdk.tar.xz -o iPhoneOS14.5.sdk.tar.xz
          mkdir -p $HOME/theos/sdks
          tar -xf iPhoneOS14.5.sdk.tar.xz -C $HOME/theos/sdks
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV

      - name: Build Tweak
        run: |
          export THEOS=$HOME/theos
          # السطر ده بيمسح أي مخلفات قديمة ويبني من جديد
          make clean
          make package FINALPACKAGE=1
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Hamad-Shield-File
          path: packages/*.deb
