name: CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Theos
        uses: p0009/setup-theos@main
      - name: Build
        run: |
          make package FINALPACKAGE=1
      - uses: actions/upload-artifact@v4
        with:
          name: Output-File
          path: packages/*.deb
